baseURL = "https://flexnet.ga/"
languageCode = "en-us"
title = "FlexNet- Watch FREE Movies and TV Shows Online"

[taxonomies]
  tag = "tags"
  category = "categories" 
  year = "years"
  lang = "langs"
  group = "groups"

Paginate = 20

[outputFormats]
  [outputFormats.announcements]
    baseName = "announcements"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.tags]
    baseName = "tags"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[outputs]
    page = ["json","HTML"] # A player
    # section = ["json","HTML"] # All players
    home = ["json","HTML", "announcements","tags"] # Everything

[minify]
  disableJSON = false