baseURL = "https://flexnet.ga/"
languageCode = "en-us"
title = "FlexNet- Watch FREE Movies and TV Shows Online"

[taxonomies]
  tag = "tags"
  category = "categories" 
  year = "years"
  lang = "langs"
  group = "groups"

Paginate = 20
