baseURL = {process.env.URL}
languageCode = "en-us"
title = "FlexNet- Watch FREE Movies and TV Shows Online"

[taxonomies]
  tag = "tags"
  category = "categories" 
  star = "stars" 
  year = "years"
  lang = "langs"
  group = "groups"

Paginate = 20
