baseURL = "https://flexnet.ga/"
languageCode = "en-us"
title = "FlexNet- Watch FREE Movies and TV Shows Online"

[taxonomies]
  tag = "tags"
  category = "categories" 
  year = "years"
  lang = "langs"
  group = "groups"

Paginate = 20

ignoreErrors = ["error-output-taxonomy"]

[outputFormats]
  [outputFormats.announcements]
    baseName = "announcements"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.tvshows]
    baseName = "tvshows"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.tags]
    baseName = "tags"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.movies]
    baseName = "movies"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.moviespage]
    baseName = "moviespage"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.slugs]
    baseName = "slugs"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.homepagetags]
    baseName = "homepagetags"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.alltvshows]
    baseName = "alltvshows"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[outputs]
    page = ["json","HTML"] # A player
    section = ["json","HTML"] # All players
    home = ["json","HTML", "announcements","tags","movies","slugs","homepagetags", "moviespage","tvshows","alltvshows"] # Everything
    term = ["json"] # All items from a sport

[minify]
  disableJSON = false