backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


logo_url: https://flexnet.ga/images/logo/flexnet.png

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "movies" # Used in routes, e.g., /admin/collections/blog
    label: "Movies" # Used in the UI
    folder: "content/movies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - {label: "Movie Title", name: "title", widget: "string", hint: "Movie motherfucken Name"}

      - {label: "Movie Title + Movie Year", name: "slug", widget: "string", hint: "add the motherfu*** slug you fucken slut"}

      - {label: "Movie Year", name: "year", widget: "string"}

      - {label: "Movie Story", name: "story", widget: "text"}
      
      - {label: "IMDB ID", name: "imdbid", widget: "string", hint: "The IMDB Id From the link"}

      - {label: "Movie Trailer", name: "trailer", widget: "string", default: "https://www.youtube.com/embed/"}