backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


logo_url: https://flexnet.ga/images/logo/flexnet.png

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "movies" # Used in routes, e.g., /admin/collections/blog
    label: "Movies" # Used in the UI
    folder: "content/movies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - {
          label: "Date you added this content",
          name: "date",
          widget: "date",
          hint: "The motherfucken date"
        }

      - {
          label: "Movie Title",
          name: "title",
          widget: "string",
          hint: "Movie motherfucken Name"
        }

      - {
          label: "Movie Title + Movie Year",
          name: "slug",
          widget: "string",
          hint: "add the motherfu*** slug you fucken slut"
        }

      - {
          label: "Movie Year",
          name: "year",
          widget: "string"
        }

      - {
          label: "Movie duration",
          name: "duration",
          widget: "string"
        }

      - {
          label: "Movie Rating",
          name: "rating",
          widget: "number",
          valueType: "float",
          min: 1,
          max: 10,
          step: .1,
          default: 6.8,
        }

      - {
          label: "Movie Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options: [
            "Action",
            "Family",
            "Thriller",
            "Sport",
            "Horror",
            "Biography",
            "Drama",
            "History",
            "Adventure",
            "Animation",
            "Romance",
            "Comedy",
            "Sci-Fi",
            "Fantasy",
            "Music",
            "Reality-TV",
            "Crime",
            "Mystery",
            "War"
          ]
        }

      - {
          label: "Movie Story",
          name: "story",
          widget: "text"
        }
      
      - {
          label: "Movie Stars",
          name: "stars",
          widget: "list"
        }

      - {
          label: "IMDB ID",
          name: "imdbid",
          widget: "string",
          hint: "The IMDB Id From the link"
        }

      - {
          label: "Movie Poster",
          hint: "the small poster on the imdb",
          name: "moviecover",
          widget: "string"
        }

      - {
          label: "Movie Wide Background",
          name: "moviebg",
          widget: "string"
        }



      - {
          label: "Movie Trailer",
          name: "trailer",
          widget: "string",
          default: "https://www.youtube.com/embed/",
          hint: "get any youtube trailer for that movie and copy the video Id and added it after the /embed/ in the cms"
        }



      - {
          label: "DarDarkom server",
          name: "server1",
          widget: "string",
          hint: "if dardarkom dont have the movie just leave this empty"
        }
      - {
          label: "server 2",
          name: "server2",
          widget: "string",
        }
      - {
          label: "server 3",
          name: "server3",
          widget: "string",
        }
      - {
          label: "server 4",
          name: "server4",
          widget: "string",
        }
      - {
          label: "server 5",
          name: "server5",
          widget: "string",
        }